language: java
install: true
sudo: false

install:
  - bash .travis.install-maven.sh "${MVN_VERSION}" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

addons:
  apt:
    packages:
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

matrix:
  include:
    - addons:
        apt:
          packages:
            - fluxbox
            - openjdk-6-jdk
    - jdk: openjdk6
      env:
        - JDK="OpenJDK 6"
        - MVN_VERSION="3.2.5"
    - jdk: openjdk7
      env:
        - JDK="OpenJDK 7"
        - MVN_VERSION="3.2.5"
    - jdk: oraclejdk8
      env:
        - JDK="Oracle JDK 8"
        - MVN_VERSION="3.2.5"
    - jdk: oraclejdk9
      env:
        - JDK="Oracle JDK 9"
        - MVN_VERSION="3.5.2"
        - MAVEN_OPTS="--illegal-access=warn --add-modules java.xml.bind"
    - jdk: openjdk9
      env:
        - JDK="OpenJDK 9"
        - MVN_VERSION="3.5.2"
        - MAVEN_OPTS="--illegal-access=warn --add-modules java.xml.bind"
    - jdk: openjdk10
      env:
        - JDK="OpenJDK 10"
        - MVN_VERSION="3.5.2"
        - MAVEN_OPTS="--illegal-access=warn --add-modules java.xml.bind"

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"

script:
  - mvn -X -U clean verify
  - mvn -X verify -Pwith-gui-tests

notifications:
  email: false
