language: java
install: true
sudo: false

install:
  # install maven 3.2.5
  - bash .travis.install-maven.sh "3.2.5" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

addons:
  apt:
    packages:
#      - openjdk-6-jdk
#      - openjdk-7-jdk
      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository
   - $HOME/mvn-home

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - fluxbox &> ~/fluxbox.log &
  - sleep 3

jdk:
#  - openjdk6
#  - openjdk7
#  - openjdk8
#  - oraclejdk8
  - oraclejdk9

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"
    - MAVEN_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.xml.bind"

script:
  - mvn -U clean verify
  - mvn verify -Pwith-gui-tests

notifications:
  email: false
