language: java
install: true
sudo: false

install:
  - bash .travis.install-maven.sh "${MVN_VERSION}" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  - mvn -version

# FIXME
# Automatic GUI tests fail  on Travis
# Failing command line: mvn verify -Pwith-gui-tests
#addons:
#  apt:
#    packages:
#      - fluxbox

cache:
 directories:
   - $HOME/.m2/repository

# FIXME
# Automatic GUI tests fail on Travis
# Failing command line: mvn verify -Pwith-gui-tests
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - fluxbox &> ~/fluxbox.log &
#  - sleep 3

matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
      env: MVN_VERSION="3.2.5"
    - addons:
        apt:
          packages:
            - fluxbox
            - openjdk-7-jdk
      jdk: openjdk7
      env: MVN_VERSION="3.3.9"
    - jdk: oraclejdk8
      env: MVN_VERSION="3.3.9"
    - jdk: oraclejdk9
      env:
        - MVN_VERSION="3.3.9"
        - MAVEN_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.xml.bind"

env:
  global:
    - JAVA_OPTS="-Djava.awt.headless=false"

script:
  - mvn -U clean verify
# FIXME
# Automatic GUI tests fail on Travis
#  - mvn verify -Pwith-gui-tests

notifications:
  email: false
